### ISSUE TITLE
 Add Solutions for Interview questions in c++, python and Java.

### ISSUE THREAD

**Issue by Awanit512** [Awanit512/HactoberFest-2K21-5-1-2-#2]
Also do include a proper tag in which company that question was asked, by commenting that tag at the top of the code .

**Comment by anubhav100rao** [comment]
sir I have created a pull request containing above code in all three languages. But it is showing that this issue is closed. May you suggest what should I do next.

**Comment by Awanit512** [comment]
You can create a issue and then give pr.

**Comment by supriyaohdar** [comment]
I also want to contribute, please assign this to me.
